# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  moviesapi:
    image: moviesapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5002
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5002
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
